# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='先生/女士', max_length=20, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
